# Attention: This dockerfile is used for building lucy-go image for development environment only.
FROM golang:1.18.3-bullseye

# Install dependencies
RUN apt update && apt upgrade -y && \
    apt install -y git \
    make openssh-client

WORKDIR /app

RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air

CMD air